### ISSUE TITLE
feat: bootstrapping framework across all OpenStack charts

### ISSUE THREAD

**Issue by alanmeadows** [att-comdev/openstack-helm#201]
This feature requests that we support a consistent bootstrapping request framework across all charts.

Every OpenStack service has resources that can be created within the service once it is actually up.  Our charts deploy very vanilla versions of services, and to be sure, this is the correct path for us.  However, users wishing to deploy a functional cloud will need some basic items and we want to provide a mechanism to load the items at chart install.

A few examples:

Glance currently deploys with no images and Nova does not deploy with any usable flavors.  It should contain a `bootstrap` section in `values.yaml` containing the images to inject once the glance server is up (and the appropriate job to perform the action) and Nova should come up with usable flavors for deployment.

This is just an example:

```
bootstrap:
  images: 
    ubuntu: 
      name: Ubuntu Precise 64-bit
      source: http://cloud-images.ubuntu.com/precise/current/precise-server-cloudimg-amd64-disk1.img
      min_disk: 20
      image_type: qcow
```

Nova right now has no flavors, a `bootstrap` section in `values.yaml` could create the default out of the box flavors OpenStack users expect:

```
bootstrap:
  flavors:
    m1.tiny:
      name: m1.tiny
      id: auto
      ram: 512
      disk: 20
      vcpus: 1
```
