### ISSUE TITLE
feat: charts - readjusting default values

### ISSUE THREAD

**Issue by gardlt** [att-comdev/openstack-helm#317]
**Is this a bug report or feature request?** (choose one): feature

**Kubernetes Version** (output of `kubectl version`): 1.6.*

**Development or Deployment Environment?**: both

**Release Tag or Master**: master

**Any Additional Comments**:

While working on deploying the charts in my dev environment, I have been encountering issues with resources limitations using the OSH vagrant. While debugging, the mariadb chart logs state that it was running out of resources. When looking at `mariadb/values.yaml`, the chart is asking for 20Gb * 3 replicas. This is way more than we would ever need on an development enviroment.

Readjusting the default variable sizes for our charts is needed to make sure that the environment is realist and works in our development machines.

i.e:

## mariadb

```
replicas: 1

volume:
  class_path: volume.beta.kubernetes.io/storage-class
  class_name: general
  size: 1Gi
```
