### ISSUE TITLE
Standardize Labels (name:value pair) & Replica to align with other charts

### ISSUE THREAD

**Issue by renmak** [att-comdev/openstack-helm#326]
**Is this a bug report or feature request?** (choose one): Mixed; depends on perspective

**Kubernetes Version** (output of `kubectl version`): N/A

**Helm Client and Tiller Versions** (output of `helm version`): N/A

**Development or Deployment Environment?**: N/A

**Release Tag or Master**:

**Expected Behavior**: 
As a developer and operator, it would be desirable to have standardized value.yaml in all charts. 

Nova and Neutron are considered as a sample standard helm chart. 

In following charts, Labels needs to be separated (just like replicas) to achieve parity with Nova & Neutron
**Cinder, Ceph, Glance, Heat**

**What Actually Happened**: This is what we have today in Cinder value.yaml
```
replicas:
  api: 1
  volume: 1
  scheduler: 1

labels:
  node_selector_key: openstack-control-plane
  node_selector_value: enabled

```

**How to Reproduce the Issue** (as minimally as possible):

**Any Additional Comments**:
